title: DWP Mobile Help Center
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-dwp-mobile
plugins:
  - jekyll-include-cache
baseurl: ""
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics: null
fast_build: false
offline: false
preload_pages: true
styling_options:
  primary_brand_color: "#376eee"
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: 
  logo_url: /
hide_toolbar:
  sidebar: false
  pdf: true
  github: true
folders:
  - name: /
    title: DWP Mobile Help Center
    subtitle: ""
    order:
      - My Account.md
      - Business Card.md
      - Dental Claims.md
      - E-commerce Order.md
      - Leave.md
      - Medical Bills and Claims.md
      - Resource.md
      - Temperature Declaration.md
      - Transport Claim.md
      - Visitor.md
      - Technical Support.md
      - Contact.md
  - name: /Test
    title: Test
    subtitle: ""
    order:
      - My Account.md
