title: OpenDoc Template #----> Required
remote_theme: opendocsg/opendoc-theme@v2
timezone: Asia/Singapore
repository: opendocsg/opendoc-template #----> Required
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

order: #----> Optional, order of pages in root
  - README.md
  - sample.md
document_order: #----> Optional, order of documents
  - Document 1
  - # --> leave blank to show root pages
  - AA Document 2
styling_options:
  primary_brand_color: '#444'  #----> Optional, theme color
  logo_path: /assets/logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df #----> Optional, feedback url
